# Generated by Django 4.2 on 2023-04-28 20:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
